package model.entities;
// Generated Jul 25, 2014 9:34:05 AM by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.List;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

    private Integer roleId;
    private String roleName;
    private String imagePath;
    private boolean active;
    private List<User> users = new ArrayList<User>();

    public Role() {
    }

    public Role(String roleName, boolean active) {
        this.roleName = roleName;
        this.active = active;
    }

    public Role(String roleName, String imagePath, boolean active, List<User> users) {
        this.roleName = roleName;
        this.imagePath = imagePath;
        this.active = active;
        this.users = users;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getImagePath() {
        return this.imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public List<User> getUsers() {
        return this.users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }

    @Override
    public boolean equals(Object obj) {
        return true;
    }
    
    
}
