package model.entities;
// Generated Jul 25, 2014 9:34:05 AM by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer userId;
    private Role role;
    private String userName;
    private String pwd;
    private String fullName;
    private Date birthOfDay;
    private boolean gender;
    private String idCard;
    private String address;
    private String email;
    private String phoneNumber;
    private String imagePath;
    private String idActive;
    private boolean active;
    private List<Post> posts = new ArrayList<Post>();
    private List<Project> projects = new ArrayList<Project>();

    public User() {
    }

    public User(Role role, String userName, String pwd, String fullName, boolean gender, String email, boolean active) {
        this.role = role;
        this.userName = userName;
        this.pwd = pwd;
        this.fullName = fullName;
        this.gender = gender;
        this.email = email;
        this.active = active;
    }

    public User(Role role, String userName, String pwd, String fullName, Date birthOfDay, boolean gender, String idCard, String address, String email, String phoneNumber, String imagePath, String idActive, boolean active, List<Post> posts, List<Project> projects) {
        this.role = role;
        this.userName = userName;
        this.pwd = pwd;
        this.fullName = fullName;
        this.birthOfDay = birthOfDay;
        this.gender = gender;
        this.idCard = idCard;
        this.address = address;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.imagePath = imagePath;
        this.idActive = idActive;
        this.active = active;
        this.posts = posts;
        this.projects = projects;
    }

    public User(Integer userId, Role role, String userName, String pwd, String fullName, Date birthOfDay, boolean gender, String idCard, String address, String email, String phoneNumber, String imagePath, String idActive, boolean active) {
        this.userId = userId;
        this.role = role;
        this.userName = userName;
        this.pwd = pwd;
        this.fullName = fullName;
        this.birthOfDay = birthOfDay;
        this.gender = gender;
        this.idCard = idCard;
        this.address = address;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.imagePath = imagePath;
        this.idActive = idActive;
        this.active = active;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPwd() {
        return this.pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Date getBirthOfDay() {
        return this.birthOfDay;
    }

    public void setBirthOfDay(Date birthOfDay) {
        this.birthOfDay = birthOfDay;
    }

    public boolean isGender() {
        return this.gender;
    }

    public void setGender(boolean gender) {
        this.gender = gender;
    }

    public String getIdCard() {
        return this.idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getImagePath() {
        return this.imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getIdActive() {
        return this.idActive;
    }

    public void setIdActive(String idActive) {
        this.idActive = idActive;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public List<Post> getPosts() {
        return this.posts;
    }

    public void setPosts(List<Post> posts) {
        this.posts = posts;
    }

    public List<Project> getProjects() {
        return this.projects;
    }

    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

//    @Override
//    public boolean equals(Object obj) {
//        if (obj == null) {
//            return false;
//        }
//        if (!this.getClass().equals(obj.getClass())) {
//            return false;
//        }
//
//        User obj2 = (User) obj;
//        if ((this.userId == obj2.getUserId()) && (this.userName.equals(obj2.getUserName()))
//                && this.fullName.equals(obj2.getFullName()) && this.pwd.equals(obj2.getPwd())
//                && this.birthOfDay == obj2.birthOfDay ) {
//            return true;
//        }
//        return false;
//    }
//
//    @Override
//    public int hashCode() {
//        int tmp = 0;
//        tmp = (userId + userName + fullName + pwd + birthOfDay + gender + idCard + address + email 
//                + phoneNumber + imagePath + idActive + active + role).hashCode();
//        return tmp;
//    }
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (userId == null) {
            return false;
        }
        if (!(other instanceof User)) {
            return false;
        }
        final User that = (User) other;
        return this.userId.equals(that.getUserId());
    }

    @Override
    public int hashCode() {
        return userId == null ? System.identityHashCode(this)
                : userId.hashCode();
    }

}
