package model.entities;
// Generated Jul 25, 2014 9:34:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryName;
     private boolean active;
     private Set posts = new HashSet(0);

    public Category() {
    }

	
    public Category(String categoryName, boolean active) {
        this.categoryName = categoryName;
        this.active = active;
    }
    public Category(String categoryName, boolean active, Set posts) {
       this.categoryName = categoryName;
       this.active = active;
       this.posts = posts;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    public Set getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set posts) {
        this.posts = posts;
    }

    @Override
    public boolean equals(Object obj) {
        if(obj instanceof Category){
            Category category =(Category)obj;
            return category.getCategoryId() == this.getCategoryId();
        }
        return false;
    }
    
}


