package model.entities;
// Generated Jul 25, 2014 9:34:05 AM by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

    private Integer projectId;
    private Type type;
    private String projectName;
    private String description;
    private Date startDate;
    private int duration;
    private boolean active;
    private List<User> users = new ArrayList<User>();

    public Project() {
    }

    public Project(Type type, String projectName, String description, Date startDate, int duration, boolean active) {
        this.type = type;
        this.projectName = projectName;
        this.description = description;
        this.startDate = startDate;
        this.duration = duration;
        this.active = active;
    }

    public Project(Integer projectId, Type type, String projectName, String description, Date startDate, int duration, boolean active, List<User> users) {
        this.projectId = projectId;
        this.type = type;
        this.projectName = projectName;
        this.description = description;
        this.startDate = startDate;
        this.duration = duration;
        this.active = active;
        this.users = users;
    }

    public Project(Type type, String projectName, String description, Date startDate, int duration, boolean active, List<User> users) {
        this.type = type;
        this.projectName = projectName;
        this.description = description;
        this.startDate = startDate;
        this.duration = duration;
        this.active = active;
        this.users = users;
    }

    public Integer getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public Type getType() {
        return this.type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public int getDuration() {
        return this.duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public List<User> getUsers() {
        return this.users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }

}
