package model.entities;
// Generated Jul 25, 2014 9:34:05 AM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.List;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer typeId;
     private String typeName;
     private boolean active;
     private List<Project> projects = new ArrayList<Project>();

    public Type() {
    }

	
    public Type(String typeName, boolean active) {
        this.typeName = typeName;
        this.active = active;
    }
    public Type(String typeName, boolean active, List<Project> projects) {
       this.typeName = typeName;
       this.active = active;
       this.projects = projects;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    public List<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

    @Override
    public boolean equals(Object obj) {
        return true;
    }

}


