package entity;
// Generated Jul 25, 2014 9:34:05 AM by Hibernate Tools 3.6.0

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectUserDetails generated by hbm2java
 */
@Entity
@Table(name = "project_user_details", 
        catalog = "db_judiwebsite")
public class ProjectUserDetails implements java.io.Serializable {

    private Integer projectUserId;
    private Project project;
    private User user;
    private boolean creator;

    public ProjectUserDetails() {
    }

    public ProjectUserDetails(Project project, boolean creator) {
        this.project = project;
        this.creator = creator;
    }

    public ProjectUserDetails(Project project, User user, boolean creator) {
        this.project = project;
        this.user = user;
        this.creator = creator;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "projectUserID", unique = true, nullable = false)
    public Integer getProjectUserId() {
        return this.projectUserId;
    }

    public void setProjectUserId(Integer projectUserId) {
        this.projectUserId = projectUserId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "projectID", nullable = false)
    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userID")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "creator", nullable = false)
    public boolean isCreator() {
        return this.creator;
    }

    public void setCreator(boolean creator) {
        this.creator = creator;
    }

}
